FROM caddy:2.11.4-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648

COPY ./Caddyfile /etc/caddy/Caddyfile

RUN wget -O - https://github.com/traP-jp/1m26_02-client/releases/latest/download/dist.tar.gz | tar zxv -C /usr/share/caddy/ --strip-components=2
